launchpad:
    owners:
        # Launchpad username
        LAUNCHPAD-USERNAME:
            max-age: 30
    branches:
        # Full path to repo
        LAUNCHPAD-BZR-REPO-PATH:
            review-count: 2
github:
    repos:
        GITHUB-USERNAME:
            GITHUB-PROJECT-NAME:
                review-count: 2
lp-git:
    owners:
        LAUNCHPAD-USERNAME:
            max-age: 30
    repos:
        LAUNCHPAD-GIT-REPO-PATH:
            review-count: 2
            tox: true
            parallel-tox: false
            environment: 18.04
# Define squad memberships for filtering
# Each squad maps to a list of author usernames
# this is a list of dictionaries which maps
# squad -> members (list[str])
squads: 
  YOUR_SQUAD_NAME:
    - user1
    - user2
